blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.PostList.as_view(), name="home"),
    path("add_post", views.AddPost.as_view(), name="add_post"),
    path("my_posts", views.MyPosts.as_view(), name="my_posts"),
    path(
        "continents/<slug:continent_slug>/",
        views.Continents.as_view(),
        name="continents"),
    path("delete/<slug:pk>/", views.DeletePost.as_view(), name="delete_post"),
    path("edit/<slug:pk>/", views.EditPost.as_view(), name="edit_post"),
    path(
        "favourite/<int:post_id>/toggle",
        views.toggle_favourite,
        name="toggle_favourite"),
    path(
        "favourite/<int:post_id>/remove",
        views.remove_favourite,
        name="remove_favourite"),
    path("my_favourites/", views.my_favourites, name="my_favourites"),
    path(
        "<slug:slug>/edit_comment/<int:comment_id>",
        views.comment_edit,
        name="comment_edit",
    ),
    path(
        "<slug:slug>/delete_comment/<int:comment_id>",
        views.comment_delete,
        name="comment_delete",
    ),
    path("<slug:slug>/", views.post_detail, name="post_detail"),
]

triptips/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# add +static according to instructions from pypi.org/project/django-ckeditor-5
urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path("", include("blog.urls"), name="blog-urls"),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from cloudinary.models import CloudinaryField
from django_ckeditor_5.fields import CKEditor5Field


STATUS = ((0, "Draft"), (1, "Published"))
CONTINENT = (
    (0, "South/Central America"),
    (1, "North America"),
    (2, "Europe"),
    (3, "Africa"),
    (4, "Asia"),
    (5, "Australia"),
)
# Create your models here.


def image_extension_validator(value):
    """
    Only validate if value is an uploaded file
    to avoid error if no new file uploaded.
    """
    if hasattr(value, 'name'):
        validator = FileExtensionValidator(
            allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])
        validator(value)


class Post(models.Model):
    """
    Store a single blog post entry related to a User
    """

    title = models.CharField("Title", max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    featured_image = CloudinaryField(
        "image", validators=[image_extension_validator], default="placeholder")
    content = CKEditor5Field("Post content", config_name="extends")
    excerpt = models.TextField(blank=True)
    continent = models.IntegerField(choices=CONTINENT, default=2)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.title} | written by {self.author}"


class Comment(models.Model):
    """
    Stores a single comment related to a User and Post
    """

    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter")
    body = models.TextField()
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.author}"


class Favourite(models.Model):
    """
    Stores a single favourite post related to a User and Post
    """
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="favourites")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="favourited_by")

    class Meta:
        unique_together = ("user", "post")

    def __str__(self):
        return f"{self.user} favourited {self.post}"

blog/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget
from .models import Comment, Post


class PostForm(forms.ModelForm):
    """
    Form to add a post
    """

    class Meta:
        model = Post
        fields = [
            "title",
            "featured_image",
            "content",
            "excerpt",
            "continent",
        ]

        labels = {
            "title": "Post title",
            "featured_image": "Post main image (jpg, jpeg, png, gif)",
            "excerpt": "Post intro text/ Summary",
        }


class CommentForm(forms.ModelForm):
    """
    Form to add a comment
    """

    class Meta:
        model = Comment
        fields = ("body",)
        labels = {
            "body": "Comment",
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.utils.text import slugify
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .models import Post, Comment, Favourite
from .forms import CommentForm, PostForm


# Create your views here.
class PostList(generic.ListView):
    """
    List all published posts
    """
    queryset = Post.objects.filter(status=1)
    template_name = "blog/index.html"
    paginate_by = 6


class MyPosts(LoginRequiredMixin, generic.ListView):
    """
    List the post made by the present logged in user
    """
    template_name = "blog/my_posts.html"
    paginate_by = 6

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)


class Continents(generic.ListView):
    """
    List the posts from a specific continent.
    """
    template_name = "blog/continents.html"
    paginate_by = 6

    CONTINENT_SLUGS = {
        "south-central-america": 0,
        "north-america": 1,
        "europe": 2,
        "africa": 3,
        "asia": 4,
        "australia": 5,
    }

    def get_queryset(self):
        continent_slug = self.kwargs.get("continent_slug")
        continent_id = self.CONTINENT_SLUGS.get(continent_slug)
        return Post.objects.filter(continent=continent_id, status=1)


class AddPost(LoginRequiredMixin, generic.CreateView):
    """
    Add blog post
    """

    template_name = "blog/add_post.html"
    model = Post
    form_class = PostForm
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        """Checks that slug is unique or add suffix"""
        base_slug = slugify(form.instance.title)
        slug = base_slug
        counter = 1
        while Post.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        form.instance.slug = slug
        form.instance.author = self.request.user
        response = super().form_valid(form)
        messages.success(
            self.request, "Your post has been created, awaits admin approval!"
        )
        return response


class EditPost(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    """
    View to edit a post.
    """
    template_name = "blog/edit_post.html"
    model = Post
    form_class = PostForm
    success_url = reverse_lazy("my_posts")

    def test_func(self):
        return self.request.user == self.get_object().author

    def form_valid(self, form):
        """
        Checks that slug is unique or add suffix,
        sets status to 0 (unpublished)
        """
        base_slug = slugify(form.instance.title)
        slug = base_slug
        counter = 1
        while Post.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        form.instance.slug = slug
        form.instance.status = 0
        response = super().form_valid(form)
        messages.success(
            self.request, "Your post has been updated, awaits admin approval!"
        )
        return response


class DeletePost(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    """
    View to delete a post.
    """

    model = Post
    success_url = reverse_lazy("my_posts")

    def test_func(self):
        return self.request.user == self.get_object().author

    def form_valid(self, form):
        messages.success(self.request, "Post deleted!")
        return super().form_valid(form)


def post_detail(request, slug):
    """
    Display an individual blog post.
    """

    queryset = Post.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comments = post.comments.all().order_by("-created_on")
    comment_count = post.comments.filter(approved=True).count()
    is_favourited = False

    if request.user.is_authenticated:
        is_favourited = Favourite.objects.filter(
            user=request.user, post=post).exists()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                "Comment submitted, awaits admin approval"
            )

    comment_form = CommentForm()

    return render(
        request,
        "blog/post_detail.html",
        {
            "post": post,
            "is_favourited": is_favourited,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form,
        },
    )


@login_required
def comment_edit(request, slug, comment_id):
    """
    View to edit a comment.
    """
    if request.method == "POST":
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.approved = False
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                "Comment Updated, awaits admin approval"
            )
        else:
            messages.add_message(request, messages.ERROR,
                                 "Error updating the comment!")

    return HttpResponseRedirect(reverse("post_detail", args=[slug]))


@login_required
def comment_delete(request, slug, comment_id):
    """
    View to delete a comment.
    """
    queryset = Post.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, "Comment deleted!")
    else:
        messages.add_message(
            request,
            messages.ERROR,
            "Deletion failed, you can only delete your own comments!",
        )

    return HttpResponseRedirect(reverse("post_detail", args=[slug]))


@login_required
def toggle_favourite(request, post_id):
    """
    View to add or remove a post from favourites when on post_detail.
    """
    post = get_object_or_404(Post, id=post_id)
    favourite, created = Favourite.objects.get_or_create(
        user=request.user, post=post)
    if not created:
        favourite.delete()
    return HttpResponseRedirect(reverse("post_detail", args=[post.slug]))


@login_required
def remove_favourite(request, post_id):
    """
    View to remove post from favourites when on "Favourites".
    """
    post = get_object_or_404(Post, id=post_id)
    favourite, created = Favourite.objects.get_or_create(
        user=request.user, post=post)
    if not created:
        favourite.delete()
    return HttpResponseRedirect(reverse("my_favourites"))


@login_required
def my_favourites(request):
    """
    View to list my favourites.
    """
    favourites = Favourite.objects.filter(
        user=request.user).select_related("post")
    return render(
        request, "blog/my_favourites.html", {"favourites": favourites})

blog/templates/blog/add_post.html
{% extends 'base.html' %} {% block title %}Add Post{% endblock %} {% block content %} {% load static %} {% load crispy_forms_tags %}
<div class="container">
    <form method="POST" enctype="multipart/form-data" class="form">
        <h2>Add Post</h2>
        {% csrf_token %} {{ form.media }} {{ form | crispy }}
        <div>
            <button type="submit" class="btn btn-signup">Upload Post</button>
        </div>
    </form>
</div>
{% endblock content %}

blog/templates/blog/continents.html
{% extends 'base.html' %}
{% load static %}
{% url 'continents' 'south-central-america' as south_america_url %}
{% url 'continents' 'north-america' as north_america_url %}
{% url 'continents' 'europe' as europe_url %}
{% url 'continents' 'africa' as africa_url %}
{% url 'continents' 'asia' as asia_url %}
{% url 'continents' 'australia' as australia_url %}
{% block content %}
  <!-- index content start here -->
  <!-- Hero image -->
  <div class="hero">
    <div class="hero-image-wrap">
      {% if 'south-central-america' in request.path %}<img src="{% static 'images/hero-rio.jpg' %}" alt="Hero image Rio" class="hero-image" />
    </div>
    <div class="hero-text">
      <h2>South / Central America</h2>{% elif 'north-america' in request.path %}<img src="{% static 'images/hero-america.jpg' %}" alt="Hero image America" class="hero-image" />
    </div>
    <div class="hero-text">
      <h2>North America</h2>{% elif 'europe' in request.path %}<img src="{% static 'images/hero-europe.jpg' %}" alt="Hero image Europe" class="hero-image" />
    </div>
    <div class="hero-text">
      <h2>Europe</h2>{% elif 'africa' in request.path %}<img src="{% static 'images/hero-africa.jpg' %}" alt="Hero image Africa" class="hero-image" />
    </div>
    <div class="hero-text">
      <h2>Africa</h2>{% elif 'asia' in request.path %}<img src="{% static 'images/hero-asia.jpg' %}" alt="Hero image Asia" class="hero-image" />
    </div>
    <div class="hero-text">
      <h2>Asia</h2>{% elif 'australia' in request.path %}<img src="{% static 'images/hero-australia.jpg' %}" alt="Hero image Australia" class="hero-image" />
    </div>
    <div class="hero-text">
      <h2>Australia</h2>{% endif %}
    </div>
  </div>
  <!-- Continent filtered posts -->
  <div class="container-fluid">
    <div class="filter-wrap text-center">
      <a class="{% if 'south-central-america' in request.path %}active-continent{% else %}filter{% endif %}" href="{% url 'continents' 'south-central-america' %}">South/Central America |</a>
      <a class="{% if 'north-america' in request.path %}active-continent{% else %}filter{% endif %}" href="{% url 'continents' 'north-america' %}">North America |</a>
      <a class="{% if 'europe' in request.path %}active-continent{% else %}filter{% endif %}" href="{% url 'continents' 'europe' %}">Europe |</a>
      <a class="{% if 'africa' in request.path %}active-continent{% else %}filter{% endif %}" href="{% url 'continents' 'africa' %}">Africa |</a>
      <a class="{% if 'asia' in request.path %}active-continent{% else %}filter{% endif %}" href="{% url 'continents' 'asia' %}">Asia |</a>
      <a class="{% if 'australia' in request.path %}active-continent{% else %}filter{% endif %}" href="{% url 'continents' 'australia' %}">Australia</a>
    </div>
    <div class="row">
      <div class="col-12 mt-3 left">
        <div class="row">
          {% for post in post_list %}
            <div class="col-sm-6 col-lg-4">
              <a href="{% url 'post_detail' post.slug %}" aria-label="Click to view {{ post.title }}" class="post-link">
                <div class="card mb-4">
                  <div class="card-body">
                    <div class="image-container">
                      {% if 'placeholder' in post.featured_image.url %}
                        <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="default travel image" />
                      {% else %}
                        <img class="card-img-top" src=" {{ post.featured_image.url }}" alt="image related to {{ post.title }}" />
                      {% endif %}
                      <div class="image-flash">
                        <p class="author">Author: {{ post.author|title }}</p>
                      </div>
                    </div>
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text">{{ post.excerpt }}</p>
                    <hr />
                    <p class="card-text text-muted h6">{{ post.created_on }}</p>
                  </div>
                </div>
              </a>
            </div>
          {% empty %}
            <div>
              <h3 class="text-center">No posts written yet, add a new post <a href="{% url 'add_post' %}" aria-label="Link to create new post">here</a></h3>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% if is_paginated %}
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
            <li>
              <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Link to previous page">&laquo; Previous</a>
            </li>
          {% endif %} {% if page_obj.has_next %}
            <li>
              <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Link to next page">Next &raquo;</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>
{% endblock %}

blog/templates/blog/edit_post.html
{% extends 'base.html' %} {% block title %}Edit Post{% endblock %} {% block content %} {% load static %} {% load crispy_forms_tags %}
<div class="container">
    <form method="POST" enctype="multipart/form-data" class="form">
        <h2>Edit Post</h2>
        {% csrf_token %} {{ form.media }} {{ form | crispy }}
        <div>
            <button type="submit" class="btn btn-signup">Edit Post</button>
        </div>
    </form>
</div>
{% endblock content %}

blog/templates/blog/index.html
{% extends "base.html" %} {% load static %} {% block content %}

<!-- index content -->
<!-- Hero image -->
<div class="hero">
    <div class="hero-image-wrap">
        <img src="{% static 'images/hero-rio.jpg' %}" alt="Hero image Rio" class="hero-image">
    </div>
    <div class="hero-text text-center">
        <h2>Welcome to Trip Tips</h2>
        <p>Get inspired by others and post your tips!</p>
    </div>
</div>
<div class="container-fluid">
    <div class="row">

        <!-- Blog post cards -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-sm-6 col-lg-4">
                    <a href="{% url 'post_detail' post.slug %}" aria-label="Click to view {{ post.title }}" class="post-link">
                        <div class="card mb-4">
                            <div class="card-body">
                                <div class="image-container">
                                    {% if "placeholder" in post.featured_image.url %}
                                    <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="default travel image"> {% else %}
                                    <img class="card-img-top" src=" {{ post.featured_image.url }}" alt="image related to {{ post.title }}"> {% endif %}
                                    <div class="image-flash">
                                        <p class="author">Author: {{ post.author | title }}</p>
                                    </div>
                                </div>
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                                <hr />
                                <p class="card-text text-muted h6">{{ post.created_on}}
                                </p>
                            </div>
                        </div>
                    </a>
                </div>
                {% empty %}
                <div>
                    <h3 class="text-center">No posts written yet, add a new post <a href="{% url 'add_post' %}" aria-label="Link to create new post">here</a></h3>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Link to previous page">&laquo; Previous</a></li>
            {% endif %} {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Link to next page"> Next &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/my_posts.html
{% extends "base.html" %} {% load static %} {% block content %}

<!-- index content start here -->
<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-sm-6 col-lg-4">
                    {% if post.status == 1 and post.author == user %}
                    <a href="{% url 'post_detail' post.slug %}" aria-label="Click to view {{ post.title }}" class="post-link">
                        <div class="card mb-4">
                            <div class="card-body">
                                <div class="image-container">
                                    {% if "placeholder" in post.featured_image.url %}
                                    <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="default travel image"> {% else %}
                                    <img class="card-img-top" src=" {{ post.featured_image.url }}" alt="image related to {{ post.title }}"> {% endif %}
                                    <div class="image-flash">
                                        <p class="author">Author: {{ post.author | title }}</p>
                                    </div>
                                </div>
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                                <hr />
                                <p class="card-text text-muted h6">
                                    {{ post.created_on}}
                                </p>
                                <div class="my_posts_btn">
                                    <a href="{% url 'edit_post' post.id %}" class="btn btn-signup w-20">Edit Post</a>
                                    <a href="{% url 'delete_post' post.id %}" class="btn btn-delete w-20">Delete Post</a>
                                </div>
                            </div>
                        </div>
                    </a>{% elif post.status == 0 %}
                    <div class="card mb-4">
                        <div class="card-body faded-text">
                            <div class="image-container">
                                {% if "placeholder" in post.featured_image.url %}
                                <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="default travel image"> {% else %}
                                <img class="card-img-top" src=" {{ post.featured_image.url }}" alt="image related to {{ post.title }}"> {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ post.author | title }}</p>
                                </div>
                            </div>
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text">{{ post.excerpt }}</p>
                            <hr />
                            <p class="card-text text-muted h6">
                                {{ post.created_on}}
                            </p>
                            <div class="my_posts_btn">
                                    <a href="{% url 'edit_post' post.id %}" class="btn btn-signup w-20">Edit Post</a>
                                    <a href="{% url 'delete_post' post.id %}" class="btn btn-delete w-20">Delete Post</a>
                                </div>
                            <p class="approval-text">
                                This post is awaiting approval
                            </p>
                        </div>
                    </div>
                    {% endif %}
                </div>
                {% empty %}
                <div>
                    <h3 class="text-center">No posts written yet, add a new post <a href="{% url 'add_post' %}" aria-label="Link to create new post">here</a></h3>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Link to previous page">&laquo; Previous</a></li>
            {% endif %} {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Link to next page"> Next &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<!-- index.html content ends here -->
{% endblock %} {% block copyright %}
<p class="m-0 text-center text-white">Copyright 2025 Patrik Lundström</p>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %} {% block title %}
  {{ post.title }}
{% endblock %} {% block content %}
  {% load static %} {% load crispy_forms_tags %}
  
  <div class="container">
    <div class="row">
    <div class="image-container">
    {% if 'placeholder' in post.featured_image.url %}
      <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="default travel image" />
    {% else %}
      <img class="card-img-top" src=" {{ post.featured_image.url }}" alt="image related to {{ post.title }}" />
    {% endif %}
    <div class="image-flash">
        <h2>{{ post.title }}</h2>
        <p>Continent: {{ post.get_continent_display }}</p>
        <p>By {{ post.author }} | {{ post.created_on }}</p>
    </div>
  </div>
    
      <div class="col card mb-4 mt-3 left top">
        <div class="card-body">
          <article class="card-text">
            <!-- post content shows here -->
            {{ post.content|safe }} {% if user.is_authenticated and post.author == user %}
              <div class="">
                <a href="{% url 'edit_post' post.id %}" class="btn btn-signup w-20">Edit Post</a>
                <a href="{% url 'delete_post' post.id %}" class="btn btn-red w-20">Delete Post</a>
              </div>
            {% endif %}
          </article>
        </div>
      </div>
    </div>
    <!-- Display add favourites section and number of comments -->
    <div class="row">
      <div>
        <form action="{% url 'toggle_favourite' post.id %}" method="post" class="favorite">
          {% csrf_token %} {% if user.is_authenticated and is_favourited %}
            <button type="submit" class="btn-fav"><i class="fa-solid fa-heart"></i></button>
          {% elif user.is_authenticated and not is_favourited %}
            <button type="submit" class="btn-fav"><i class="fa-regular fa-heart"></i></button>
          {% endif %}
        </form>
      </div>
      <div class="col-12">
        <hr />
      </div>
      <div class="col-12">
        <strong><i class="fa-regular fa-comments"></i> {{ comment_count }}</strong>
      </div>
    </div>
    <!-- Display the comments -->
    <div class="row">
      <div class="col-md-8 card mb-4 mt-3">
        <h3>Comments:</h3>
        <div class="card-body">
          <!-- Loop to iterate through every comment -->
          {% for comment in comments %}
            <div class="p-2 comments
                {% if not comment.approved and comment.author == user %}
                faded-text
              {% elif not comment.approved %}
                 d-none
              {% endif %}">
              <p class="font-weight-bold">
                {{ comment.author|title }}
                <span class="font-weight-normal">{{ comment.created_on }}</span> wrote:
              </p>
              <div id="comment{{ comment.id }}">{{ comment.body|linebreaks }}</div>
              {% if not comment.approved and comment.author == user %}
                <p class="approval-text">This comment is awaiting approval</p>
              {% endif %} {% if user.is_authenticated and comment.author == user %}
                <button class="btn btn-comment-edit" data-comment_id="{{ comment.id }}">Edit</button>
                <button class="btn btn-comment-delete" data-comment_id="{{ comment.id }}">Delete</button>
              {% endif %}
            </div>
          {% endfor %}
        </div>
      </div>
      <!-- Add comments -->
      <div class="col-md-4 card mb-4 mt-3">
        <div class="card-body">
          {% if user.is_authenticated %}
            <h3>Leave a comment:</h3>
            <p>Posting as: {{ user.username }}</p>
            <form id="commentForm" method="post">
              {{ comment_form|crispy }} {% csrf_token %}
              <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
            </form>
          {% else %}
            <p>
              <a href="{% url 'account_login' %}">Log in</a>to leave a comment
            </p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <!-- Delete comment confirmation modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">Are you sure you want to delete your comment? This action cannot be undone.</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <a id="deleteConfirm" href="#" class="btn btn-delete">Delete</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %} {% block extras %}
  <script src="{% static 'js/script.js' %}"></script>
{% endblock %}